name: ci

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        node-version:
        - 15.x
        - 14.x # Changing this? Remind to keep linter conditions below and in publish.yml aligned.
        - 12.x
        - 10.x
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run dev-up
    - run: npm run build
      # Only run linter once, for faster CI. Align the verisons of Node here with above and publish.yml.
    - if: matrix.platform == 'ubuntu-latest' && matrix.node-version == '14.x'
      run: npm run lint
    - run: npm test
  
  # Docker build image and push to DockerHub
  docker:
    needs: build

    env:
      IMAGE_ID: ${{ secrets.DOCKERHUB_USERNAME }}/nativefier
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_ID:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Tag and Push
        run: |
          # Tag docker image the commit SHA
          docker tag $IMAGE_ID:latest $IMAGE_ID:${GITHUB_SHA::8}
          
          # Push the images to the registry
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:${GITHUB_SHA::8}
    
