name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:
    branches:
      - master

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: nativefier

jobs:
  push:
    name: Build and Push

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      
        # Build docker image
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

        # Log into Github container registry (ghcr.io)
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        # Push image to registry
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')


          echo IMAGE_ID=$IMAGE_ID

          # Tag docker image with latest and the commit SHA
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker tag $IMAGE_NAME $IMAGE_ID:GITHUB_SHA
          # Push the images to the registry
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:GITHUB_SHA
