name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build-and-push:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Login to GitHub Container Registry
          uses: docker/login-action@v1 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.CR_PAT }}
            
        -
          name: Build and push
          uses: docker/build-push-action@v2
          id: docker_build
          with:
            context: .
            file: Dockerfile
            tags: ghcr.io/snpranav/nativefier
            push: true
